---
# tasks file for Roles/common
- name : Update Ubuntu repo
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Upgrade pakketen van Ubuntu
  apt:
    upgrade: dist
    force_apt_get: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Manage firewall to accept SSH on Ubuntu, restart if necessary
  ufw:
    rule: allow
    port: '22'
    proto: tcp
  notify:
    - restart_firewall_ubuntu
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Manage firewall to accept SSH on Ubuntu,443
  ufw:
    rule: allow
    port: '443'
    proto: tcp
  notify:
    - restart_firewall_ubuntu
  when: ansible_facts['distribution'] == "Ubuntu"

- name : Update packages for CentOS 
  yum:
    name: '*'
    state: latest
  when: ansible_facts['distribution'] == "CentOS"

- name: Manage firewall to accept SSH on CentOS, restart if necessary
  firewalld:
    port: 22/tcp
    state: enabled
    permanent: yes
  notify:
    - restart_firewall_centos
  when: ansible_facts['distribution'] == "CentOS"

- name: Manage firewall to accept SSH on CentOS, 443
  firewalld:
    port: 443/tcp
    state: enabled
    permanent: yes
  notify:
    - restart_firewall_centos
  when: ansible_facts['distribution'] == "CentOS"

