---

- name: Update software
  hosts: webservers
  roles:
   - common
   
- name: Install docker
  hosts: webservers
  roles:
   - docker

- name: Login and pull image
  hosts: webservers
  roles:
   - containers



